"""
Client implementation of a pathfinder.  Provides the interface to do pathfinding for UI and navigation.
Manages the client caching strategy
"""
from collections import defaultdict
import sys

from eve.common.script.sys.idCheckers import IsKnownSpaceSystem, IsTriglavianSystem, IsWormholeSystem
from evePathfinder.pathfinderconst import UNREACHABLE_JUMP_COUNT


class ClientPathfinder(object):
    def __init__(self, pathfinderCore, standardStateInterface, autopilotStateInterface,
                 convertStationIDToSolarSystemIDIfNecessaryMethod, getCurrentSystemMethod):
        # this is the standard pathfinding interface used when user autopilot settings are not relevant
        self._standardStateInterface = standardStateInterface
        # this is the interface used when user settings are taken into account (sec penalty, route settings)
        self._autopilotStateInterface = autopilotStateInterface
        self.pathfinderCore = pathfinderCore
        self.pathfinderCore.SetGetCachedEntryMethod(self.GetCachedEntry)
        self.pathfinderCacheByStateInterfaceAndRouteType = defaultdict(self.pathfinderCore.CreateCacheEntry)
        self.ConvertStationIDToSolarSystemIDIfNecessary = convertStationIDToSolarSystemIDIfNecessaryMethod
        self.GetCurrentSystem = getCurrentSystemMethod

    def UpdatePathfinderCore(self, pathfinderCore):
        self.pathfinderCore = pathfinderCore
        self.pathfinderCore.SetGetCachedEntryMethod(self.GetCachedEntry)
        self.pathfinderCacheByStateInterfaceAndRouteType.default_factory = self.pathfinderCore.CreateCacheEntry

    def GetCachedEntry(self, stateInterface, fromID):
        return self.pathfinderCacheByStateInterfaceAndRouteType[(id(stateInterface), stateInterface.GetRouteType())]

    def SetSecurityPenaltyFactor(self, securityPenalty):
        self._autopilotStateInterface.SetSecurityPenaltyFactor(securityPenalty)

    def SetPodKillAvoidance(self, pkAvoid):
        """
        Set pod kill avoidance to the specified value. If a change occurs,
        cache is invalidated, and will be refreshed
        """
        self._autopilotStateInterface.SetPodKillAvoidance(pkAvoid)

    def SetTriglavianTaleAvoidance(self, avoid):
        self._autopilotStateInterface.SetTriglavianTaleAvoidance(avoid)

    def SetEdencomSystemsAvoidance(self, avoid):
        self._autopilotStateInterface.SetEdencomSystemsAvoidance(avoid)

    def SetSystemAvoidance(self, pkAvoid=None):
        self._autopilotStateInterface.SetSystemAvoidance(pkAvoid)

    def GetAvoidanceItems(self):
        """
            returns a list of solar systems, constellations and regions on the character's autopilot avoidance list
            note: If the user has not changed his settings this function will return DEFAULT_AVOIDANCE
        """
        return self._autopilotStateInterface.GetAvoidanceItems(expandSystems=False)

    def GetExpandedAvoidanceItems(self):
        """
        Get avoidance items and expand solar systems and constellation to actual systems
        """
        return self._autopilotStateInterface.GetAvoidanceItems(expandSystems=True)

    def AddAvoidanceItem(self, itemID):
        """
            Adds a new solar system, constellation or region to the character's Avoidance List
        """
        items = self.GetAvoidanceItems()
        items.append(itemID)
        self._autopilotStateInterface.SetAvoidanceItems(items)

    def RemoveAvoidanceItem(self, itemID):
        """
            Removes a solar system, constellation or region from the character's Avoidance List
        """
        items = self.GetAvoidanceItems()

        if itemID in items:
            items.remove(itemID)
            self._autopilotStateInterface.SetAvoidanceItems(items)
            self.SetSystemAvoidance()

    def SetAutopilotRouteType(self, routeType):
        """
        Set the route type dictating what security rating is considered valid
        for pathfinding.
        """
        self._autopilotStateInterface.SetRouteType(routeType)

    def GetAutopilotRouteType(self):
        """
        Returns the current route type
        """
        return self._autopilotStateInterface.GetRouteType()

    def GetCompleteWaypointList(self, waypointWithOnlySystems, waypoints):
        """
        Takes a list of waypoints generated by the pathfinder and a list of waypoints and merges them together
        to create a list of waypoints with the inbetween routes

        :param waypointWithOnlySystems: a list of paths.
                        Each path is a list of [origin, [autopilotRoute], destination]
        :param waypoints: The requested waypoints, this is a list of destinations
        :return: A list of sequential waypoints that shows the complete path from an origin to a destination
                (or multiple destinations)
        """
        completeWaypointList = []
        # we can ignore the first waypoint in the waypoint list, since we always start from our origin
        currentWaypointIndex = 1
        currentSolarSystem = None
        for pathWithSolarSystems in waypointWithOnlySystems:
            if len(pathWithSolarSystems) == 0:
                continue

            pathEndpoint = pathWithSolarSystems[-1]
            pathStartPoint = pathWithSolarSystems[0]
            currentWaypoint = waypoints[currentWaypointIndex]

            if pathWithSolarSystems[-1] != currentWaypoint:
                pathWithSolarSystems.append(currentWaypoint)

            if pathStartPoint == currentSolarSystem:
                pathWithSolarSystems.pop(0)

            currentSolarSystem = pathEndpoint

            completeWaypointList.extend(pathWithSolarSystems)
            currentWaypointIndex += 1
        return completeWaypointList

    def GetWaypointPath(self, waypoints):
        solarSystemWaypoints = list(map(self.ConvertStationIDToSolarSystemIDIfNecessary, waypoints))
        waypointListsContainingOnlySystems = self.pathfinderCore.GetListOfWaypointPaths(
            self._autopilotStateInterface,
            self.GetCurrentSystem(),
            solarSystemWaypoints
        )

        return self.GetCompleteWaypointList(waypointListsContainingOnlySystems, waypoints)

    def GetJumpCountsBetweenSystemPairs(self, sourceDestinationPairList):
        return self.pathfinderCore.GetJumpCountsBetweenSystemPairs(self._standardStateInterface, sourceDestinationPairList)

    def _GetPathBetween(self, stateInterface, fromID, toID):
        if not IsKnownSpaceSystem(fromID) or not IsKnownSpaceSystem(toID):
            return []

        return self.pathfinderCore.GetPathBetween(stateInterface, fromID, toID)

    def GetPathBetween(self, fromID, toID):
        return self._GetPathBetween(self._standardStateInterface, fromID, toID)

    def GetAutopilotPathBetween(self, fromID, toID):
        convertedFromID = self.ConvertStationIDToSolarSystemIDIfNecessary(fromID)
        convertedToID = self.ConvertStationIDToSolarSystemIDIfNecessary(toID)
        return self._GetPathBetween(self._autopilotStateInterface, convertedFromID, convertedToID)

    def _GetJumpCount(self, stateInterface, fromID, toID):
        if fromID is None or toID is None:
            return None
        if fromID == toID:
            # When travelling within the same system (even wormholes) the distance should always be zero
            return 0
        if not IsKnownSpaceSystem(fromID) or not IsKnownSpaceSystem(toID):
            return UNREACHABLE_JUMP_COUNT

        return self.pathfinderCore.GetJumpCountBetween(stateInterface, fromID, toID)

    def GetJumpCount(self, fromID, toID):
        return self._GetJumpCount(self._standardStateInterface, fromID, toID)

    def GetAutopilotJumpCount(self, fromID, toID):
        return self._GetJumpCount(self._autopilotStateInterface, fromID, toID)

    def GetJumpCountFromCurrent(self, toID):
        return self._GetJumpCount(self._standardStateInterface, self.GetCurrentSystem(), toID)

    def _GetSystemsWithinJumpRange(self, stateInterface, fromID, jumpCountMin, jumpCountMax):
        if not IsKnownSpaceSystem(fromID):
            return {}

        return self.pathfinderCore.GetSystemsWithinJumpRange(stateInterface, fromID, jumpCountMin, jumpCountMax)

    def GetSystemsWithinJumpRange(self, fromID, jumpCountMin, jumpCountMax):
        """
        Returns a map[jumpCount, list of systems] that have a jump count that is >= minCount and < maxCount
        """
        return self._GetSystemsWithinJumpRange(self._standardStateInterface, fromID, jumpCountMin, jumpCountMax)

    def GetSystemsWithinAutopilotJumpRange(self, fromID, jumpCountMin, jumpCountMax):
        """
        Returns a map[jumpCount, list of systems] that have a jump count that is >= minCount and < maxCount, taking
        into account Autopilot settings
        """
        return self._GetSystemsWithinJumpRange(self._autopilotStateInterface, fromID, jumpCountMin, jumpCountMax)

    def _GetNoRouteFoundText(self, solarSystemID, shouldConsiderAutopilotSettings=False):
        import localization
        if IsTriglavianSystem(solarSystemID) or IsWormholeSystem(solarSystemID):
            # This solar system can be accessed via wormholes or is a wormhole system.
            return localization.GetByLabel("UI/Generic/NoGateToGateRoute")
        else:
            clientPathfinderService = sm.GetService("clientPathfinderService")
            if shouldConsiderAutopilotSettings:
                if clientPathfinderService.GetAutopilotPathBetween(const.solarSystemJita, solarSystemID):
                    # This is somewhere in connected known space.
                    return localization.GetByLabel("UI/Generic/NoGateToGateRoute")
            else:
                if clientPathfinderService.GetPathBetween(const.solarSystemJita, solarSystemID):
                    # This is somewhere in connected known space.
                    return localization.GetByLabel("UI/Generic/NoGateToGateRoute")
        # No path exists to Jita and it's not a wormhole system or in Pochven.
        # Must be off the grid, such as Polaris.
        return localization.GetByLabel("UI/Generic/Unreachable")

    def GetNoRouteFoundText(self, solarSystemID):
        """
        Get the appropriate text showing that no route could be calculated to the system
        from wherever. Assumes no path exists to this system from wherever you start.
        """
        return self._GetNoRouteFoundText(solarSystemID, shouldConsiderAutopilotSettings=False)

    def GetNoRouteFoundTextAutopilot(self, solarSystemID):
        """
        Get the appropriate text showing that no route could be calculated to the system
        from wherever. Assumes no path exists to this system from wherever you start.
        Takes into account Autopilot settings.
        """
        return self._GetNoRouteFoundText(solarSystemID, shouldConsiderAutopilotSettings=True)
